

/*
 * Filename: sc_speed_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_speed_type.h"



/* USER CODE START SC_SPEED_INCLUDE */

/* USER CODE END SC_SPEED_INCLUDE */


/*
* description: Signalclass
* name: sc_speed
* shortname: speed
*/

/* USER CODE START SC_SPEED_USERDEFINITIONS */

/* USER CODE END SC_SPEED_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_SPEED signal  ****************
 *****************************************************************************************/
 
 

/**
 * Default IN driver API
 */
inline RC_t SC_SPEED_driverIn(SC_SPEED_data_t *const data)
{
	/* USER CODE START driverInSC_SPEED */

	//Read data from the MCAL driver

	//Scale it to the application type

	return RC_SUCCESS;
	/* USER CODE END driverInSC_SPEED */
}
/**
 * Default OUT driver API
 */
inline RC_t SC_SPEED_driverOut(const SC_SPEED_data_t  *const data)
{
	/* USER CODE START driverOutSC_SPEED */
    if(data->mySpeed > 4)
    {
        PWM_Green_WriteCompare(data->mySpeed);
    }
    else 
    {
        PWM_Green_WriteCompare(0);
    }

	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
	/* USER CODE END driverOutSC_SPEED */
}



