

/*
 * Filename: sc_clock_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_clock_type.h"



/* USER CODE START SC_CLOCK_INCLUDE */

/* USER CODE END SC_CLOCK_INCLUDE */


/*
* description: Signalclass
* name: sc_clock
* shortname: clock
*/

/* USER CODE START SC_CLOCK_USERDEFINITIONS */

/* USER CODE END SC_CLOCK_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_CLOCK signal  ****************
 *****************************************************************************************/
 
 
/**
 * Default OUT driver API
 */
inline RC_t SC_CLOCK_driverOut(const SC_CLOCK_data_t  *const data)
{
	/* USER CODE START driverOutSC_CLOCK */

    char arr_min [10]  = " ";
    char arr_hour [10] = " ";
    sprintf(arr_min  , "%02d", data->clockValue.mins);
    sprintf(arr_hour , "%02d", data->clockValue.hours);
    
    tftDisplay(arr_hour,arr_min);

	//Scale application data to drive format
    
	//Write scaled data to driver

	return RC_SUCCESS;
	/* USER CODE END driverOutSC_CLOCK */
}



