

/*
 * Filename: swc_brakelight.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_brakelight.h"
#include "watchdog.h"


/* USER CODE START SWC_BRAKELIGHT_INCLUDE */

/* USER CODE END SWC_BRAKELIGHT_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_BRAKELIGHT_USERDEFINITIONS */

/* USER CODE END SWC_BRAKELIGHT_USERDEFINITIONS */



/*
* component: swc_brakeLight
* cycletime: 100
* description: Runnable
* events: ev_speed_onData
* name: BRAKELIGHT_setBrakeLight_run
* shortname: setBrakeLight
* signalIN: so_speed
* signalOUT: so_brakeLight
* task: tsk_io
*/
void BRAKELIGHT_setBrakeLight_run(RTE_event ev){
	
	/* USER CODE START BRAKELIGHT_setBrakeLight_run */
    SC_SPEED_data_t engineValue = RTE_SC_SPEED_get( &SO_SPEED_signal );
    SC_BRAKELIGHT_data_t brakeValue = SC_BRAKELIGHT_INIT_DATA;
    
    /*
     * Check for speed signal before brake light to set status bit 
     * If not set, the 7th bit in LED_RED mask(0x40) will cause an issue when the this bit value changes
    */
    if(engineValue.mySpeed <= 4)
        brakeValue.status = TRUE;
    else 
        brakeValue.status = FALSE;
    
    //RTE_SC_SPEED_set(&SO_BRAKELIGHT_signal, engineValue );
    RTE_SC_BRAKELIGHT_set(&SO_BRAKELIGHT_signal,brakeValue);
    RTE_SC_BRAKELIGHT_pushPort( &SO_BRAKELIGHT_signal );
    
     WD_Alive(3);
    /* USER CODE END BRAKELIGHT_setBrakeLight_run */
}

/* USER CODE START SWC_BRAKELIGHT_FUNCTIONS */

/* USER CODE END SWC_BRAKELIGHT_FUNCTIONS */

