

/*
 * Filename: swc_control.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_control.h"
#include "watchdog.h"



/* USER CODE START SWC_CONTROL_INCLUDE */

/* USER CODE END SWC_CONTROL_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_CONTROL_USERDEFINITIONS */

/* USER CODE END SWC_CONTROL_USERDEFINITIONS */



/*
* component: swc_control
* cycletime: 100
* description: Runnable
* events: ev_joystick_onData
* name: CONTROL_calcControl_run
* shortname: calcControl
* signalIN: so_joystick
* signalOUT: so_speed
* task: tsk_control
*/
void CONTROL_calcControl_run(RTE_event ev){
	
	/* USER CODE START CONTROL_calcControl_run */
    SC_JOYSTICK_data_t controlValue = RTE_SC_JOYSTICK_get(&SO_JOYSTICK_signal);
    
    SC_SPEED_data_t speedDouble;
    if(controlValue.y > 4)
    {        
        speedDouble.mySpeed = (2*controlValue.y); 
    }        
    else
    {
        speedDouble.mySpeed = 4;  
    }
    
    RTE_SC_SPEED_set(&SO_SPEED_signal, speedDouble );
    
     WD_Alive(1);
    
    /* USER CODE END CONTROL_calcControl_run */
}

/* USER CODE START SWC_CONTROL_FUNCTIONS */

/* USER CODE END SWC_CONTROL_FUNCTIONS */

