
/*
 * Filename: swc_brakelight.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SWC_BRAKELIGHT
#define _H_DEFINE_SWC_BRAKELIGHT

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_BRAKELIGHT_INCLUDES */

/* USER CODE END SWC_BRAKELIGHT_INCLUDES */



/* USER CODE START SWC_BRAKELIGHT_USERDEFINITIONS */

/* USER CODE END SWC_BRAKELIGHT_USERDEFINITIONS */


/*
* component: swc_brakeLight
* cycletime: 100
* description: Runnable
* events: ev_speed_onData
* name: BRAKELIGHT_setBrakeLight_run
* shortname: setBrakeLight
* signalIN: so_speed
* signalOUT: so_brakeLight
* task: tsk_io
*/
void BRAKELIGHT_setBrakeLight_run(RTE_event ev);


#endif