

/*
 * Filename: swc_engine.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_engine.h"
#include "watchdog.h"


/* USER CODE START SWC_ENGINE_INCLUDE */

/* USER CODE END SWC_ENGINE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_ENGINE_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_USERDEFINITIONS */



/*
* component: swc_engine
* cycletime: 100
* description: Runnable
* events: 
* name: ENGINE_setEngine_run
* shortname: setEngine
* signalIN: so_speed
* signalOUT: so_engine
* task: tsk_io
*/
void ENGINE_setEngine_run(RTE_event ev){
	
	/* USER CODE START ENGINE_setEngine_run */
    SC_SPEED_data_t engineValue = SC_SPEED_INIT_DATA;
    
    if(RTE_SC_SPEED_getAge(&SO_SPEED_signal) > 1000)
    {
        engineValue.mySpeed = 0;
        SO_SPEED_signal.age = 0;
    }
    else 
    {
        engineValue = RTE_SC_SPEED_get( &SO_SPEED_signal );
    }
    
    RTE_SC_SPEED_set(&SO_ENGINE_signal, engineValue );
    
    RTE_SC_SPEED_pushPort(&SO_ENGINE_signal);
    
     WD_Alive(2);
    /* USER CODE END ENGINE_setEngine_run */
}

/* USER CODE START SWC_ENGINE_FUNCTIONS */

/* USER CODE END SWC_ENGINE_FUNCTIONS */

