

/*
 * Filename: swc_remote.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_remote.h"
#include "watchdog.h"



/* USER CODE START SWC_REMOTE_INCLUDE */

/* USER CODE END SWC_REMOTE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_REMOTE_USERDEFINITIONS */

/* USER CODE END SWC_REMOTE_USERDEFINITIONS */



/*
* component: swc_remote
* cycletime: 500
* description: Runnable
* events: 
* name: REMOTE_readJoystick_run
* shortname: readJoystick
* signalIN: 
* signalOUT: so_joystick
* task: tsk_io
*/
void REMOTE_readJoystick_run(RTE_event ev){
	
	/* USER CODE START REMOTE_readJoystick_run */
     //SC_JOYSTICK_data_t myJoystick = SC_JOYSTICK_INIT_DATA;
    
    WD_Alive(0);
    RTE_SC_JOYSTICK_pullPort( &SO_JOYSTICK_signal);
    
    
    
    /* Hardcoded joystick values to check flow
        myJoystick.x = 5;
        myJoystick.y = 5;
    */
    
    //Write the data back to the object
    //RC_t result = RTE_SC_JOYSTICK_set(&SO_JOYSTICK_signal, myJoystick);
    /* USER CODE END REMOTE_readJoystick_run */
}

/* USER CODE START SWC_REMOTE_FUNCTIONS */

/* USER CODE END SWC_REMOTE_FUNCTIONS */

