
/*
 * Filename: swc_clock.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SWC_CLOCK
#define _H_DEFINE_SWC_CLOCK

#include "project.h"
#include "global.h"
#include "rte_types.h"
#include "tft.h"

    
/*Enum to define all the events for the state machine.*/
typedef enum  {
    EV_NONE,
    EV_KEYLEFT,
    EV_KEYRIGHT,
    EV_KEYRIGHTLONGPRESS,
    EV_250MS,
    EV_1MIN
    
} EVENT_ENUM_t; 

typedef enum  {
   CLOCK_C_ISDISPLAYING,
   CLOCK_C_ISEDITINGHOURS,
   CLOCK_C_ISEDITINGMINUTES,
} CLOCK_state_t;

//pointer connection between container and widget



typedef enum  {
   W_MINUTES,
   W_HOURS
} WIDGET_type_t;
 
typedef struct  {
   TFT_colors_t F_BG_COLOR;
   TFT_colors_t F_TEXT_COLOR;
} CLOCK_font_t; 

typedef struct
{
    uint8_t mins;
    uint8_t hours;
    CLOCK_font_t font_mins;
    CLOCK_font_t font_hours;
} CLOCK_active_widget_t;

/* USER CODE START SWC_CLOCK_INCLUDES */

/* USER CODE END SWC_CLOCK_INCLUDES */


/* USER CODE START SWC_CONTROL_USERDEFINITIONS */





/* USER CODE START SWC_CLOCK_USERDEFINITIONS */

/* USER CODE END SWC_CLOCK_USERDEFINITIONS */


/*
* component: swc_clock
* cycletime: 50
* description: Runnable
* events: 
* name: CLOCK_input_run
* shortname: input
* signalIN: 
* signalOUT: so_event
* task: tsk_io
*/
void CLOCK_input_run(RTE_event ev);

/*
* component: swc_clock
* cycletime: 0
* description: Runnable
* events: ev_event_onData|ev_1min|ev_250ms
* name: CLOCK_control_run
* shortname: control
* signalIN: so_event
* signalOUT: so_clock
* task: tsk_control
*/
void CLOCK_control_run(RTE_event ev);

/*
* component: swc_clock
* cycletime: 250
* description: Runnable 
* events: 
* name: CLOCK_display_run
* shortname: display
* signalIN: so_clock
* signalOUT: so_display
* task: tsk_tft
*/
void CLOCK_display_run(RTE_event ev);


void CLOCK__action_initClock();



void tftDisplay( char* time_hours, char* time_mins);


#endif