

/*
 * Filename: swc_clock.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */




/* USER CODE START SWC_CLOCK_INCLUDE */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_clock.h"
#include "tft.h"
#include "statemachine.h"
#include "sp_common.h"
#include "stdio.h"

/* USER CODE END SWC_CLOCK_INCLUDE */

volatile uint8_t m_hours = 0;
volatile uint8_t m_mins = 0;



CLOCK_active_widget_t w_currentTime;
/*static functions defined*/

extern SC_EVENT_data_t buttonStatus;


/*ENUM to define all the states of the state machine*/

typedef enum  {
    CLOCK_W_ISDISPLAYING,
    CLOCK_W_ISEDITING,
    CLOCK_W_ISAUTOINCREMENT
} WIDGET_state_t;


static void CLOCK__dispatch_KL_Hours();
static void CLOCK__increment1Minute();
static void CLOCK__dispatch_KL_HoursMin();
static void CLOCK__dispatch_KR_Hours();
static void CLOCK__dispatch_KRLP_Hours();
static void CLOCK__dispatch_250MS_Hours();

static void CLOCK__dispatch_KL_Min();
static void CLOCK__dispatch_KR_Min();
static void CLOCK__dispatch_KRLP_Min();
static void CLOCK__dispatch_250MS_Min();

static void CLOCK__dispatchWrapper(EVENT_ENUM_t ev, WIDGET_type_t activeWidget);

static void CLOCK_incrementWidget ();
static void CLOCK_setEditFonts ();
static void CLOCK_setDisplayFonts ();


/** ---------------------------------- Transitions ---------------------------------------- **/
/*===================================   CONTAINER   =========================================*/

/**  ===== CLOCK_C_ISDISPLAYING ====   */
const STATE_stateInnerTransitionTable_t STATE_CLOCK_C_ISDISPLAYING_Transitions = {
/*    Event                 ToState         Guard                       Action                       */
    { EV_KEYLEFT, CLOCK_C_ISEDITINGHOURS,      0,           CLOCK__dispatch_KL_Hours},
	{ EV_1MIN,	  CLOCK_C_ISDISPLAYING,        0,           CLOCK__increment1Minute },
};


/**  ===== IS_EDITINGHOURS ====   */
const STATE_stateInnerTransitionTable_t STATE_CLOCK_C_ISEDITINGHOURS_Transitions = {
/*    Event                          ToState                 		 Guard                       Action                       */
    { EV_KEYLEFT,                CLOCK_C_ISEDITINGMINUTES,      0,                         CLOCK__dispatch_KL_HoursMin },
	{ EV_KEYRIGHT,	             CLOCK_C_ISEDITINGHOURS,      0, /*Todo add guard */ 	 CLOCK__dispatch_KR_Hours    },
    { EV_KEYRIGHTLONGPRESS,	     CLOCK_C_ISEDITINGHOURS,      0, /*Todo add guard */ 	 CLOCK__dispatch_KRLP_Hours  },
    { EV_250MS,	                 CLOCK_C_ISEDITINGHOURS,      0, /*Todo add guard */ 	 CLOCK__dispatch_250MS_Hours },
};

/**  ===== IS_EDITINGMINS ====   */
const STATE_stateInnerTransitionTable_t STATE_CLOCK_C_ISEDITINGMINS_Transitions = {
/*    Event                          ToState                 		 Guard                       Action                       */
    { EV_KEYLEFT,                CLOCK_C_ISDISPLAYING,          0,                          CLOCK__dispatch_KL_Min    },
	{ EV_KEYRIGHT,	             CLOCK_C_ISEDITINGMINUTES,      0, /*Todo add guard */ 	    CLOCK__dispatch_KR_Min    },
    { EV_KEYRIGHTLONGPRESS,	     CLOCK_C_ISEDITINGMINUTES,      0, /*Todo add guard */ 	    CLOCK__dispatch_KRLP_Min  },
    { EV_250MS,	                 CLOCK_C_ISEDITINGMINUTES,      0, /*Todo add guard */ 	    CLOCK__dispatch_250MS_Min },
};

/**
 * Note: The casting is required because
 * 	- We cannot store element of unknown size inside a class unless it is placed at the end of the memory section
 * 	- At the same time, we need the array of undefined size to allocate memory in the assignments above
 * 	- As a consequence, some nasty casts are required to translate the address of the array into a normal pointer
 */


static const STATE_stateOuterTransitionTable_t CONTROL_CLOCK_Transitions = {
    /*fromState                             Pointer to table                                Size of table [Elements] */   
    { CLOCK_C_ISDISPLAYING,       &STATE_CLOCK_C_ISDISPLAYING_Transitions,                sizeof(STATE_CLOCK_C_ISDISPLAYING_Transitions)/sizeof(STATE_stateInnerTransition_t)    },
    { CLOCK_C_ISEDITINGHOURS,     &STATE_CLOCK_C_ISEDITINGHOURS_Transitions,              sizeof(STATE_CLOCK_C_ISEDITINGHOURS_Transitions)/sizeof(STATE_stateInnerTransition_t)  },
    { CLOCK_C_ISEDITINGMINUTES,   &STATE_CLOCK_C_ISEDITINGMINS_Transitions,               sizeof(STATE_CLOCK_C_ISEDITINGMINS_Transitions)/sizeof(STATE_stateInnerTransition_t)   },
};

//static const uint16_t CONTROL_Connection_Transitions_size = sizeof(CONTROL_Connection_Transitions)/sizeof(STATE_stateOuterTransition_t);

/* USER CODE START SWC_CLOCK_USERDEFINITIONS */

/* USER CODE END SWC_CLOCK_USERDEFINITIONS */

/** ---------------------------------- Action Table ------------------------------------------- **/

static const STATE_stateAction_t CONTROL_CLOCK_StateActions[] = {
/* fromState                           Entry                           Exit    */
  { CLOCK_C_ISDISPLAYING,     0,        0   }
};

//static const uint16_t CONTROL_Connection_StateActions_size = sizeof(CONTROL_Connection_StateActions)/sizeof(STATE_stateAction_t);



/* ---------------------------------- WIDGET ---------------------------------------- */

/**  ===== CLOCK_W_ISDISPLAYING ====   */
static const STATE_stateInnerTransitionTable_t state_CLOCK_W_ISDISAPLAYING_Transitions = {
/*    Event                 ToState                 		 Guard                       Action                       */
    { EV_KEYLEFT,       CLOCK_W_ISEDITING,                     0,                  CLOCK_setEditFonts},
	{ EV_1MIN,          CLOCK_W_ISDISPLAYING,                  0,                  CLOCK_incrementWidget},
};


/**  ===== CLOCK_W_ISEDITING ====   */
static const STATE_stateInnerTransitionTable_t state_CLOCK_W_ISEDITING_Transitions = {
/*    Event                         ToState                 		      Guard                       Action                       */
    {EV_KEYRIGHT,                CLOCK_W_ISEDITING,                        0,                          CLOCK_incrementWidget},
    {EV_KEYRIGHTLONGPRESS,       CLOCK_W_ISAUTOINCREMENT,                  0,                          0},
    {EV_KEYLEFT,                 CLOCK_W_ISDISPLAYING,                     0,                          CLOCK_setDisplayFonts},
   
};

/**  ===== CLOCK_W_ISAUTOINCREMENT ====   */
static const STATE_stateInnerTransitionTable_t state_CLOCK_W_ISAUTOINCREMENT_Transitions = {
/*    Event                   ToState                 		 Guard                       Action                       */
    { EV_KEYRIGHT,             CLOCK_W_ISEDITING,             0,                          CLOCK_incrementWidget},
    { EV_250MS,                CLOCK_W_ISAUTOINCREMENT,       0,                          CLOCK_incrementWidget},
};


/**
 * Note: The casting is required because
 * 	- We cannot store element of unknown size inside a class unless it is placed at the end of the memory section
 * 	- At the same time, we need the array of undefined size to allocate memory in the assignments above
 * 	- As a consequence, some nasty casts are required to translate the address of the array into a normal pointer
 */
static const STATE_stateOuterTransitionTable_t CLOCK_Widget_Transitions = {
/*    fromState                             Pointer to table                            Size of table [Elements]    */
    { CLOCK_W_ISDISPLAYING,             &state_CLOCK_W_ISDISAPLAYING_Transitions,       sizeof(state_CLOCK_W_ISDISAPLAYING_Transitions)/sizeof(STATE_stateInnerTransition_t)    },
    { CLOCK_W_ISEDITING,                &state_CLOCK_W_ISEDITING_Transitions,           sizeof(state_CLOCK_W_ISEDITING_Transitions)/sizeof(STATE_stateInnerTransition_t)     },
    { CLOCK_W_ISAUTOINCREMENT,          &state_CLOCK_W_ISAUTOINCREMENT_Transitions,     sizeof(state_CLOCK_W_ISAUTOINCREMENT_Transitions)/sizeof(STATE_stateInnerTransition_t) }
};
static const uint16_t CLOCK_Widget_Transitions_size = sizeof(CLOCK_Widget_Transitions)/sizeof(STATE_stateOuterTransition_t);

/* ---------------------------------- Action Table ------------------------------------------- */


static const STATE_stateAction_t CLOCK_WIDGET_StateActions[] = {
/*  fromState                           Entry                           Exit    */
  { STATE(CLOCK_W_ISDISPLAYING),     0,        0   }
};


/** ---------------------------------- State Machine Object --------------------------------- **/


/**
 * The connection state machine object 
 **/



STATE_t CONTROL_ContainerFSM = {
    &CONTROL_CLOCK_Transitions,
    sizeof(CONTROL_CLOCK_Transitions)/sizeof(STATE_stateOuterTransition_t),    
    &CONTROL_CLOCK_StateActions,
    sizeof(CONTROL_CLOCK_StateActions)/sizeof(STATE_stateAction_t),    
    STATE(CLOCK_C_ISDISPLAYING)    
};

STATE_t CONTROL_WidgetFSM = {
    &CLOCK_Widget_Transitions,
    sizeof(CLOCK_Widget_Transitions)/sizeof(STATE_stateOuterTransition_t),    
    &CLOCK_WIDGET_StateActions,
    sizeof(CLOCK_WIDGET_StateActions)/sizeof(STATE_stateAction_t),    
    STATE(CLOCK_W_ISDISPLAYING)    
};

    


void CLOCK__action_initClock()
{ 
    SC_CLOCK_data_t controlSignal;
    controlSignal.StateMachine_ptr = &CONTROL_ContainerFSM;
    RTE_SC_CLOCK_set(&SO_CLOCK_signal,controlSignal); 
    
    SC_CLOCK_data_t dispatchSignal;
    dispatchSignal.StateMachine_ptr = &CONTROL_WidgetFSM;
    dispatchSignal.clockValue.hours = 0;
    dispatchSignal.clockValue.mins = 0;     
       
    
    dispatchSignal.clockValue.font_hours.F_TEXT_COLOR = WHITE;
    dispatchSignal.clockValue.font_hours.F_BG_COLOR = BLACK;
    dispatchSignal.clockValue.font_mins.F_TEXT_COLOR = WHITE;
    dispatchSignal.clockValue.font_mins.F_BG_COLOR = BLACK;    
    RTE_SC_CLOCK_set(&SO_CLOCK_signal,dispatchSignal); 
    TFT_setTextSize(4); 
    tftDisplay("00", "00");
     
       
}


/*
* component: swc_clock
* cycletime: 50
* description: Runnable
* events: 
* name: CLOCK_input_run
* shortname: input
* signalIN: 
* signalOUT: so_event
* task: tsk_io
*/
void CLOCK_input_run(RTE_event ev){
	
	/* USER CODE START CLOCK_input_run */
    static uint8_t longPressTick = 0;

	/* USER CODE START TSK_IO_TASKBOBY_PRE */
    if(1 == BUTTON_2_Read())
    {        
        longPressTick++;
    }
    if(longPressTick >= 20)
    { 
        buttonStatus.buttonPress = EV_KEYRIGHTLONGPRESS;
        SetRelAlarm(alarm_250msEv,250,250);
        RTE_SC_EVENT_set(&SO_EVENT_signal,buttonStatus); 
        longPressTick = 0;
    }
    /* USER CODE END CLOCK_input_run */
}

/*
* component: swc_clock
* cycletime: 0
* description: Runnable
* events: ev_event_onData|ev_1min|ev_250ms
* name: CLOCK_control_run
* shortname: control
* signalIN: so_event
* signalOUT: so_clock
* task: tsk_control
*/
void CLOCK_control_run(RTE_event ev){
	
	/* USER CODE START CLOCK_control_run */
    
    //Read the button data from the RTE
    
    SC_EVENT_data_t eventSignal = RTE_SC_EVENT_get(&SO_EVENT_signal); 
    RTE_SC_EVENT_getThreadSafe(&SO_EVENT_signal,&eventSignal);
    
    
    if((ev_250ms & ev) == ev_250ms)
    {
        eventSignal.buttonPress = EV_250MS; 
    }
     
    if((ev_1min & ev) == ev_1min)
    {
        eventSignal.buttonPress = EV_1MIN;
    }
    
    
    //Execute Container State Machine
	STATE_processEvent(&CONTROL_ContainerFSM, eventSignal.buttonPress);    
    
    /* USER CODE END CLOCK_control_run */
}

/*
* component: swc_clock
* cycletime: 250
* description: Runnable 
* events: 
* name: CLOCK_display_run
* shortname: display
* signalIN: so_clock
* signalOUT: so_display
* task: tsk_tft
*/
void CLOCK_display_run(RTE_event ev){
	
	/* USER CODE START CLOCK_display_run */
    SC_CLOCK_data_t displaySignal = SC_CLOCK_INIT_DATA;
    
    //Resource to avoid race around condition
    RTE_SC_CLOCK_getThreadSafe(&SO_CLOCK_signal,&displaySignal);
    displaySignal = RTE_SC_CLOCK_get(&SO_CLOCK_signal);
    
    RTE_SC_CLOCK_set(&SO_DISPLAY_signal, displaySignal );
    
    RTE_SC_CLOCK_pushPort(&SO_DISPLAY_signal);
    
    
    /* USER CODE END CLOCK_display_run */
}

/* USER CODE START SWC_CLOCK_FUNCTIONS */


static void CLOCK__dispatch_KL_Hours()
{
    CLOCK__dispatchWrapper(EV_KEYLEFT, W_HOURS);         
}

static void CLOCK__increment1Minute()
{
    CLOCK__dispatchWrapper(EV_1MIN, W_MINUTES); 
}

static void CLOCK__dispatch_KL_HoursMin()
{
    CLOCK__dispatchWrapper(EV_KEYLEFT, W_HOURS);
    CLOCK__dispatchWrapper(EV_KEYLEFT, W_MINUTES);
}

static void CLOCK__dispatch_KR_Hours()
{    
    CLOCK__dispatchWrapper(EV_KEYRIGHT, W_HOURS);
}

static void CLOCK__dispatch_KRLP_Hours()
{ 
    CLOCK__dispatchWrapper(EV_KEYRIGHTLONGPRESS, W_HOURS);
}

static void CLOCK__dispatch_250MS_Hours()
{     
    CLOCK__dispatchWrapper(EV_250MS, W_HOURS);    
}

static void CLOCK__dispatch_250MS_Min()
{    
    CLOCK__dispatchWrapper(EV_250MS, W_MINUTES);
}

static void CLOCK__dispatch_KRLP_Min()
{  
    CLOCK__dispatchWrapper(EV_KEYRIGHTLONGPRESS, W_MINUTES);
}

static void CLOCK__dispatch_KL_Min()
{
    CLOCK__dispatchWrapper(EV_KEYLEFT, W_MINUTES);    
}

static void CLOCK__dispatch_KR_Min()
{  
    CLOCK__dispatchWrapper(EV_KEYRIGHT, W_MINUTES);     
}



static void CLOCK_incrementWidget ()
{     
    
    SC_CLOCK_data_t clockSignal = RTE_SC_CLOCK_get(&SO_CLOCK_signal);
    if(clockSignal.activeWidget == W_HOURS)
    {
        if(m_hours < 23)
            m_hours ++;
        else 
            m_hours = 0;
        clockSignal.clockValue.hours = m_hours;
        
    }
    else if(clockSignal.activeWidget == W_MINUTES)
    {
        if(m_mins < 59)
            m_mins ++;
        else 
        {  
            if(clockSignal.StateMachine_ptr->m_state == CLOCK_C_ISDISPLAYING)
            {
                if(m_hours < 23)
                    m_hours++;
                else 
                    m_hours = 0;
                clockSignal.clockValue.hours = m_hours;  
            }
            m_mins = 0;
        }
        clockSignal.clockValue.mins = m_mins;  
    }
    RTE_SC_CLOCK_set(&SO_CLOCK_signal,clockSignal);    
}

static void CLOCK_setEditFonts ()
{  
    if(SO_CLOCK_signal.value.activeWidget == W_HOURS)
    {
        SO_CLOCK_signal.value.clockValue.font_hours.F_TEXT_COLOR = BLACK;
        SO_CLOCK_signal.value.clockValue.font_hours.F_BG_COLOR = WHITE;
        SO_CLOCK_signal.value.clockValue.font_mins.F_TEXT_COLOR = WHITE;
        SO_CLOCK_signal.value.clockValue.font_mins.F_BG_COLOR = BLACK;
    }
    else if(SO_CLOCK_signal.value.activeWidget == W_MINUTES)
    {
        SO_CLOCK_signal.value.clockValue.font_hours.F_TEXT_COLOR = WHITE;
        SO_CLOCK_signal.value.clockValue.font_hours.F_BG_COLOR = BLACK;
        SO_CLOCK_signal.value.clockValue.font_mins.F_TEXT_COLOR = BLACK;
        SO_CLOCK_signal.value.clockValue.font_mins.F_BG_COLOR = WHITE;
    }
    
}

static void CLOCK_setDisplayFonts ()
{  
    SO_CLOCK_signal.value.clockValue.font_hours.F_TEXT_COLOR = WHITE;
    SO_CLOCK_signal.value.clockValue.font_hours.F_BG_COLOR = BLACK;
    SO_CLOCK_signal.value.clockValue.font_mins.F_TEXT_COLOR = WHITE;
    SO_CLOCK_signal.value.clockValue.font_mins.F_BG_COLOR = BLACK;
      
    
}

static void CLOCK__dispatchWrapper(EVENT_ENUM_t ev, WIDGET_type_t activeWidget)
{           
    SO_CLOCK_signal.value.activeWidget = activeWidget;
    STATE_processEvent(&CONTROL_WidgetFSM, ev);        
}
/* USER CODE END SWC_CLOCK_FUNCTIONS */

void tftDisplay( char* time_hours, char* time_mins)
{    
    TFT_setCursor(5, 40);
    TFT_setColors(SO_CLOCK_signal.value.clockValue.font_hours.F_TEXT_COLOR,SO_CLOCK_signal.value.clockValue.font_hours.F_BG_COLOR);
    TFT_print(time_hours);
    TFT_setColors(WHITE,BLACK);
    TFT_print(":");
    TFT_setColors(SO_CLOCK_signal.value.clockValue.font_mins.F_TEXT_COLOR,SO_CLOCK_signal.value.clockValue.font_mins.F_BG_COLOR);
    TFT_print(time_mins);
}

