
/*
 * Filename: tsk_control.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_TSK_CONTROL
#define _H_DEFINE_TSK_CONTROL

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_CONTROL_INCLUDES */

/* USER CODE END TSK_CONTROL_INCLUDES */



/*
* description: To perform clock logic operations
* events: ev_event_onData|ev_1min|ev_250ms
* mode: Event
* name: tsk_control
* shortname: control
* signalpoolsRO: sp_common
* signalpoolsRW: sp_common
* tickEvent: ev_event_onData
* timertickperiod: 0
*/
DeclareTask(tsk_control);


#endif