
/*
 * Filename: tsk_tft.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_TSK_TFT
#define _H_DEFINE_TSK_TFT

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_TFT_INCLUDES */

/* USER CODE END TSK_TFT_INCLUDES */



/*
* description: Task doing work
* events: 
* mode: Cyclic 
* name: tsk_tft
* shortname: tft
* signalpoolsRO: sp_common
* signalpoolsRW: sp_common
* tickEvent: 0
* timertickperiod: 250
*/
DeclareTask(tsk_tft);


#endif