

/*
 * Filename: tsk_tft.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "tsk_tft.h"



/* USER CODE START TSK_TFT_INCLUDE */

/* USER CODE END TSK_TFT_INCLUDE */

#include "swc_clock.h"



/* USER CODE START TSK_TFT_USERDEFINITIONS */

/* USER CODE END TSK_TFT_USERDEFINITIONS */

/*******************************************************************************
 * Runnable Tables from Activation Engine
 *******************************************************************************/

/* Cyclic Table */

const RTE_cyclicTable_t RTE_cyclicActivationTable_tsk_tft[] = {
	{ CLOCK_display_run, 250 },	//Runnable 
};
const uint16_t RTE_cyclicActivation_tsk_tft_size = sizeof (RTE_cyclicActivationTable_tsk_tft) / sizeof(RTE_cyclicTable_t); 

/*******************************************************************************
 * Task Body
 *******************************************************************************/


/*
* description: Task doing work
* events: 
* mode: Cyclic 
* name: tsk_tft
* shortname: tft
* signalpoolsRO: sp_common
* signalpoolsRW: sp_common
* tickEvent: 0
* timertickperiod: 250
*/
TASK(tsk_tft)
{
	/* ticktime of the task */
	static uint32_t ticktime = 0;
	
    
		/* USER CODE START TSK_TFT_TASKBOBY_PRE */

		/* USER CODE END TSK_TFT_TASKBODY_PRE */
        
            //Process Cyclic table on tick
            RTE_ProcessCyclicTable(RTE_cyclicActivationTable_tsk_tft, RTE_cyclicActivation_tsk_tft_size, ticktime);

			ticktime += 250;
			if (ticktime > 0xFFFFFF00) ticktime = 0;

	
		
		//Process data driven events
		
		/* USER CODE START TSK_TFT_TASKBODY_POST */

		/* USER CODE END TSK_TFT_TASKBODY_POST */

}


/*******************************************************************************
 * Interrupt Service Routines
 *******************************************************************************/

/* USER CODE START TSK_TFT_ISR */

/* USER CODE END TSK_TFT_ISR */

